#!/bin/sh
#
#  Default policy method for Remote Control Policy Region 
#
#  This method prints the filtering mode for the list of possible targets.
#
#  Possible modes are:
#	node		(show only managed nodes)
#	pcnode	(show only PC managed nodes)
#	nwnode      (show only netware clients) 
#	epnode      (show only LCF Endpoints)   
#	all		(show all)
#
#	XXX-locked	(show XXX only, and the user cannot change the setting)
#			(eg.  "pcnode-locked")

echo "all"

exit 0
