--
-- Licensed Materials - Property of IBM 
-- 5698-SWD 
-- (C)IBM Corp. 2000, 2008 All Rights Reserved 
-- All Rights Reserved. US Government Users Restricted Rights 
-- Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
--
--
-- IBM Tivoli Configuration Manager 4.3.1
-- Activity Planner
-- Database schema creation script 
-- Platform: Oracle
--

spool fs_plans_ora_schema.log;

--DROP VIEW V_TGT_ACT_ST;

--DROP VIEW V_TGT_ACT_GW_ST;

--DROP VIEW V_TGT_ACT_DEP_ST;

--DROP VIEW V_PLAN_STATUS_EX;

--DROP VIEW V_PLAN_STATUS;

--DROP VIEW V_ACT_STATUS_EX;

--DROP VIEW V_ACT_STATUS;

--DROP VIEW V_ACT_ST;

--DROP VIEW V_STATUS_TGT;

--DROP VIEW V_STATUS_FILTER;

--DROP VIEW V_TGT_GW_FLTR ;

--DROP TABLE USER_PARAMETER;

--DROP TABLE PLUGIN_FILE_INFO;

--DROP TABLE ACTIVITY_TARGET;

--DROP TABLE ACT_TARGET_SPEC;

--DROP TABLE ACT_STATUS_TGT;

--DROP TABLE ACTIVITY_STATUS;

--DROP TABLE ACT_PLAN_STATUS;

--DROP TABLE APPL_ERRLEV;

--DROP TABLE ACT_PARAMETER;

--DROP TABLE ACT_LAYOUT;

--DROP TABLE VARIABLE;

--DROP TABLE PLAN_TARGET;

--DROP TABLE PLAN_TARGET_SPEC;

--DROP TABLE EXECUTION_WINDOW;

--DROP TABLE ACTIVITY;

--DROP TABLE ACTIVITY_PLAN;

--DROP TABLE APPL_OPERATION;

--DROP TABLE PLAN_LOCKS;



-- 
-- TABLE: USER_PARAMETER
--

CREATE TABLE USER_PARAMETER(
    PRINCIPLE 	 VARCHAR(80)    NOT NULL,
    QUERY_NAME     VARCHAR(255)    NOT NULL,
    NAME		 VARCHAR(128)  ,
    MIN_REC_NUM        VARCHAR(128)  ,
    MAX_REC_NUM        VARCHAR(128)  ,
    STATUS  	 VARCHAR(128)  ,
    MIN_STARTED        VARCHAR(128)  ,
    MAX_STARTED        VARCHAR(128)  ,
    MIN_COMPLETED	 VARCHAR(128)  ,
    MAX_COMPLETED	 VARCHAR(128)  ,
    PARAM VARCHAR(2),
    DEFAULT_FILTER VARCHAR(2),
    PRIMARY KEY(PRINCIPLE,QUERY_NAME)
) 
;



-- 
-- TABLE: ACT_LAYOUT 
--

CREATE TABLE ACT_LAYOUT(
    PLAN_ID        VARCHAR2(80)     NOT NULL,
    ACTIVITY_ID    NUMBER           NOT NULL,
    USER_ID        VARCHAR2(64)     NOT NULL,
    X_COORD        NUMBER           NOT NULL,
    Y_COORD        NUMBER           NOT NULL,
    PRIMARY KEY (PLAN_ID,ACTIVITY_ID,USER_ID)
) 
;


-- 
-- TABLE: ACT_PARAMETER 
--

CREATE TABLE ACT_PARAMETER(
    PLAN_ID           VARCHAR2(80)     NOT NULL,
    ACTIVITY_ID       NUMBER           NOT NULL,
    PARAMETER_NAME    VARCHAR2(128)    NOT NULL,
    PARAMETER_DATA    VARCHAR2(128)    NOT NULL,
    PRIMARY KEY (PLAN_ID,PARAMETER_NAME,ACTIVITY_ID)
) 
;


-- 
-- TABLE: ACT_PLAN_STATUS 
--

CREATE TABLE ACT_PLAN_STATUS(
    PLAN_ID            VARCHAR2(80)     NOT NULL,
    REC_NUM            NUMBER           NOT NULL,
    START_TIME         DATE,
    COMPLETION_TIME    DATE,
    STATUS             NUMBER           NOT NULL,
    PREV_STATUS        NUMBER           NOT NULL,
    PRIMARY KEY (PLAN_ID,REC_NUM)
) 
;


-- 
-- TABLE: ACT_STATUS_TGT 
--

CREATE TABLE ACT_STATUS_TGT(
    PLAN_ID            VARCHAR2(80)     NOT NULL,
    ACTIVITY_ID        NUMBER           NOT NULL,
    REC_NUMBER         NUMBER           NOT NULL,
    TARGET_NAME        VARCHAR2(128)    NOT NULL,
    TARGET_OID         VARCHAR2(64)     NOT NULL,
    STATUS             NUMBER           NOT NULL,
    PREV_STATUS        NUMBER           NOT NULL,
    GATEWAY_OID        VARCHAR2(64),
    DEPOT_OID          VARCHAR2(64),
    GATEWAY_LABEL      VARCHAR2(128),
    DEPOT_LABEL        VARCHAR2(128),
    START_TIME         DATE,
    COMPLETION_TIME    DATE,
    ERROR_INFO         VARCHAR2(251),
    ERROR_CODE         NUMBER       ,
    PRIMARY KEY (PLAN_ID,ACTIVITY_ID,REC_NUMBER,TARGET_NAME)
) 
;


-- 
-- TABLE: ACT_TARGET_SPEC 
--

CREATE TABLE ACT_TARGET_SPEC(
    PLAN_ID        VARCHAR2(80)      NOT NULL,
    ACTIVITY_ID    NUMBER            NOT NULL,
    SPEC_NUM       NUMBER            NOT NULL,
    SPEC_USE       CHAR(1)           NOT NULL,
    SPEC_TYPE      CHAR(1)           NOT NULL,
    TARGET_SPEC    VARCHAR2(2000),
    PRIMARY KEY (PLAN_ID,ACTIVITY_ID,SPEC_NUM,SPEC_USE)
) 
;


-- 
-- TABLE: ACTIVITY_TARGET
--

CREATE TABLE ACTIVITY_TARGET(
    PLAN_ID        VARCHAR2(80)      NOT NULL,
    ACTIVITY_ID    NUMBER            NOT NULL,
    SPEC_NUM       NUMBER            NOT NULL,
    TARGET_NAME    VARCHAR2(128)     NOT NULL,
    PRIMARY KEY (PLAN_ID,ACTIVITY_ID,SPEC_NUM,TARGET_NAME)
) 
;


-- 
-- TABLE: ACTIVITY 
--

CREATE TABLE ACTIVITY(
    PLAN_ID             VARCHAR2(80)     NOT NULL,
    ACTIVITY_ID         NUMBER           NOT NULL,
    DESCRIPTION         VARCHAR2(251),
    SPEC_COMP           CHAR(1),
    TGT_RESOURCE_TYPE   NUMBER,
    NAME                VARCHAR2(128)     NOT NULL,
    CONDITION           LONG VARCHAR,
    APPLICATION_TYPE    VARCHAR2(32)     NOT NULL,
    OPERATION_TYPE      VARCHAR2(32)     NOT NULL,
    PRIMARY KEY (PLAN_ID,ACTIVITY_ID)
) 
;


-- 
-- TABLE: ACTIVITY_PLAN 
--

CREATE TABLE ACTIVITY_PLAN(
    PLAN_ID              VARCHAR2(80)     NOT NULL,
    IS_TEMPLATE          CHAR(1)          NOT NULL,
    IS_PAUSED            CHAR(1)          NOT NULL,
    PRIORITY             NUMBER           NOT NULL,
    NAME                 VARCHAR2(128)    NOT NULL,
    STOP_ON_ERROR        NUMBER           NOT NULL,
    IS_CANC_CUTOFF       CHAR(1)          NOT NULL,
    IS_POST_NOTICE       CHAR(1)          NOT NULL,
    DESCRIPTION          VARCHAR2(251),
    SPEC_COMP            CHAR(1),
    TGT_RESOURCE_TYPE    NUMBER,
    REC_STOP_ON_ERROR    NUMBER,
    REC_STOP_OVERLAP     CHAR(1),
    REC_EXPIRE_TIME      DATE,
    RELATIVE_EXP_TIME    VARCHAR2(16),
    REC_TYPE             NUMBER,
    DAYS_OF_WEEK         VARCHAR2(16),
    DAYS_OF_MONTH        VARCHAR2(128),
    REC_BY_DATE_INT      CHAR(16),
    REC_BY_TIME_INT      CHAR(16),
    IS_DYN_RESOLV        CHAR(1),
    MAIL_ADDRESS         VARCHAR2(251),
    NOT_BEFORE_TIME      DATE,
    NOT_AFTER_TIME       DATE,
    RELATIVE_NOT_AFTER   VARCHAR2(16),
    ON_TERMINATION       NUMBER,
    CREDENTIALS          LONG VARCHAR,
    NOTIFY_DATE		DATE,
    REL_NOTIFY_DATE VARCHAR2(16),	
    PRIMARY KEY (PLAN_ID)
) 
;


-- 
-- TABLE: ACTIVITY_STATUS 
--

CREATE TABLE ACTIVITY_STATUS(
    PLAN_ID             VARCHAR2(80)     NOT NULL,
    ACTIVITY_ID         NUMBER           NOT NULL,
    REC_NUMBER          NUMBER           NOT NULL,
    STATUS              NUMBER           NOT NULL,
    PREV_STATUS         NUMBER           NOT NULL,
    PRIORITY            NUMBER           NOT NULL,
    TIME_ENQUEUED       DATE,
    APPL_SPEC_ACT_ID    VARCHAR2(64),
    START_TIME          DATE,
    COMPLETION_TIME     DATE,
    PRIMARY KEY (PLAN_ID,REC_NUMBER,ACTIVITY_ID)
) 
;


-- 
-- TABLE: APPL_OPERATION 
--

CREATE TABLE APPL_OPERATION(
    APPLICATION_TYPE    VARCHAR2(32)    NOT NULL,
    PACKAGE             VARCHAR2(251),
    DESCRIPTION         VARCHAR2(251),
    CLASSPATH           LONG VARCHAR,       
    PRIMARY KEY (APPLICATION_TYPE)
) 
;


-- 
-- TABLE: PLUGIN_FILE_INFO
--
CREATE TABLE PLUGIN_FILE_INFO(
    APPLICATION_TYPE    VARCHAR2(32)    NOT NULL,
    FILE_NAME           VARCHAR2(251)   NOT NULL,
    CRC32               VARCHAR2(32)    NOT NULL,
    PRIMARY KEY (APPLICATION_TYPE, FILE_NAME)
) 
;

-- 
-- TABLE: APPL_ERRLEV 
--

CREATE TABLE APPL_ERRLEV(
    APPLICATION_TYPE    VARCHAR2(32)    NOT NULL,
    RET_CODE            INTEGER        NOT NULL,
    ERROR_LEVEL         INTEGER         NOT NULL,
    PRIMARY KEY (APPLICATION_TYPE,RET_CODE)
) 
;


-- 
-- TABLE: EXECUTION_WINDOW 
--

CREATE TABLE EXECUTION_WINDOW(
    PLAN_ID        VARCHAR2(80)     NOT NULL,
    ACTIVITY_ID    NUMBER           NOT NULL,
    START_TIME     DATE             NOT NULL,
    END_TIME       DATE             NOT NULL,
    PRIMARY KEY (PLAN_ID,ACTIVITY_ID,START_TIME)
) 
;


-- 
-- TABLE: PLAN_TARGET_SPEC 
--

CREATE TABLE PLAN_TARGET_SPEC(
    PLAN_ID        VARCHAR2(80)      NOT NULL,
    SPEC_NUM       NUMBER            NOT NULL,
    SPEC_USE       CHAR(1)           NOT NULL,
    SPEC_TYPE      CHAR(1)           NOT NULL,
    TARGET_SPEC    VARCHAR2(2000),
    PRIMARY KEY (PLAN_ID,SPEC_NUM,SPEC_USE)
) 
;


-- 
-- TABLE: PLAN_TARGET
--

CREATE TABLE PLAN_TARGET(
    PLAN_ID        VARCHAR2(80)      NOT NULL,
    SPEC_NUM       NUMBER            NOT NULL,
    TARGET_NAME    VARCHAR2(128)     NOT NULL,
    PRIMARY KEY (PLAN_ID,SPEC_NUM,TARGET_NAME)
) 
;


-- 
-- TABLE: VARIABLE 
--

CREATE TABLE VARIABLE(
    NAME          VARCHAR2(128)     NOT NULL,
    PLAN_ID       VARCHAR2(80)      NOT NULL,
    CURR_VALUE    VARCHAR2(2000)    NOT NULL,
    PRIMARY KEY (NAME,PLAN_ID)
) 
;

-- 
-- TABLE: PLAN_LOCKS
--

CREATE TABLE PLAN_LOCKS(
    PLAN_ID            VARCHAR2(80)     NOT NULL,
    NAME               VARCHAR2(128)     NOT NULL,
    APMUSER            VARCHAR2(128)    NOT NULL,
    MANAGED_NODE       VARCHAR2(128)    NOT NULL,
    LOCK_DATE          DATE            NOT NULL,
	PRIMARY KEY (PLAN_ID)
) 
;



--
--VIEW V_STATUS_TGT 
--

CREATE VIEW V_STATUS_TGT (TARGET_NAME, ACTIVITY_NAME, PLAN_NAME ,  STATUS, REC_NUM, START_TIME, COMPLETION_TIME,DEPOT_LABEL )AS
SELECT AST.TARGET_NAME, A.NAME , AP.NAME, 
AST.STATUS,AST.REC_NUMBER,
AST.START_TIME,AST.COMPLETION_TIME ,AST.DEPOT_LABEL 
FROM ACTIVITY A, ACTIVITY_PLAN AP,ACT_STATUS_TGT AST 
WHERE A.ACTIVITY_ID = AST.ACTIVITY_ID AND A.PLAN_ID = AST.PLAN_ID AND AP.PLAN_ID = AST.PLAN_ID
;

--
--VIEW V_TGT_GW_FLTR 
--
CREATE VIEW V_TGT_GW_FLTR AS   
 SELECT AC.TARGET_NAME,AC.STATUS, AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.GATEWAY_LABEL, 
 COUNT(*) COUNTER, MIN(START_TIME) START_TIME, MAX(COMPLETION_TIME) COMPLETION_TIME
 FROM ACT_STATUS_TGT AC  
 GROUP BY AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.GATEWAY_LABEL, AC.STATUS,AC.TARGET_NAME
;

-- 
-- VIEW: V_ACT_ST 
--

CREATE VIEW V_ACT_ST AS    
SELECT AC.PLAN_ID, AC.REC_NUMBER, AC.STATUS, COUNT(*) COUNTER    
FROM ACTIVITY_STATUS AC  
GROUP BY AC.PLAN_ID,  AC.REC_NUMBER, AC.STATUS
;

-- 
-- VIEW: V_ACT_STATUS 
--

CREATE VIEW V_ACT_STATUS AS    
SELECT AC.NAME, AC.CONDITION, ACT.STATUS, ACT.PRIORITY, ACT.TIME_ENQUEUED, 
       ACT.APPL_SPEC_ACT_ID, ACT.START_TIME, ACT.COMPLETION_TIME, ACT.PLAN_ID, 
       ACT.ACTIVITY_ID, ACT.REC_NUMBER, AC.APPLICATION_TYPE, AC.OPERATION_TYPE, 
       AC.DESCRIPTION, AC.SPEC_COMP, ACT.PREV_STATUS    FROM ACTIVITY AC, ACTIVITY_STATUS ACT    
WHERE ACT.PLAN_ID = AC.PLAN_ID AND ACT.ACTIVITY_ID = AC.ACTIVITY_ID
;

-- 
-- VIEW: V_ACT_STATUS_EX 
--
CREATE VIEW V_ACT_STATUS_EX AS    
 SELECT AC.NAME, AC.CONDITION, ACT.STATUS, ACT.PRIORITY, ACT.TIME_ENQUEUED, 
        ACT.APPL_SPEC_ACT_ID, ACT.START_TIME, ACT.COMPLETION_TIME, ACT.PLAN_ID, 
        ACT.ACTIVITY_ID, ACT.REC_NUMBER, AC.APPLICATION_TYPE, AC.OPERATION_TYPE, 
        AC.DESCRIPTION, ACT.PREV_STATUS, 
        (SELECT COUNT(*)  
        FROM ACT_STATUS_TGT AST 
         WHERE AST.PLAN_ID = ACT.PLAN_ID AND AST.ACTIVITY_ID = ACT.ACTIVITY_ID 
               AND AST.REC_NUMBER = ACT.REC_NUMBER) AS TARGETS, 
        (SELECT COUNT(DISTINCT GATEWAY_LABEL)  
        FROM ACT_STATUS_TGT AST 
         WHERE AST.PLAN_ID = ACT.PLAN_ID AND AST.ACTIVITY_ID = ACT.ACTIVITY_ID 
               AND AST.REC_NUMBER = ACT.REC_NUMBER) AS GATEWAYS , 
        (SELECT COUNT(DISTINCT DEPOT_LABEL)  
        FROM ACT_STATUS_TGT AST 
         WHERE AST.PLAN_ID = ACT.PLAN_ID AND AST.ACTIVITY_ID = ACT.ACTIVITY_ID 
               AND AST.REC_NUMBER = ACT.REC_NUMBER) AS DEPOTS
 FROM ACTIVITY AC, ACTIVITY_STATUS ACT  
WHERE ACT.PLAN_ID = AC.PLAN_ID AND ACT.ACTIVITY_ID = AC.ACTIVITY_ID 
;

-- 
-- VIEW: V_PLAN_STATUS 
--

CREATE VIEW V_PLAN_STATUS AS    
SELECT PL.START_TIME, PL.COMPLETION_TIME, PL.STATUS, AC.IS_TEMPLATE, AC.PRIORITY, AC.NAME, 
       AC.STOP_ON_ERROR, AC.IS_CANC_CUTOFF, AC.DESCRIPTION, AC.SPEC_COMP, AC.REC_STOP_ON_ERROR, AC.REC_STOP_OVERLAP, 
       AC.REC_TYPE, AC.DAYS_OF_WEEK, AC.DAYS_OF_MONTH, AC.REC_BY_DATE_INT, AC.REC_BY_TIME_INT, 
       AC.IS_DYN_RESOLV, AC.MAIL_ADDRESS, AC.IS_POST_NOTICE, PL.PLAN_ID, PL.REC_NUM, AC.NOT_BEFORE_TIME, 
       AC.NOT_AFTER_TIME, PL.PREV_STATUS, AC.IS_PAUSED, AC.REC_EXPIRE_TIME, AC.ON_TERMINATION, AC.CREDENTIALS,
       AC.RELATIVE_NOT_AFTER, AC.RELATIVE_EXP_TIME,AC.NOTIFY_DATE,AC.REL_NOTIFY_DATE,AC.TGT_RESOURCE_TYPE
FROM ACT_PLAN_STATUS PL, ACTIVITY_PLAN AC 
   WHERE PL.PLAN_ID = AC.PLAN_ID  AND AC.IS_TEMPLATE = 'S'
;





-- 
-- VIEW: V_PLAN_STATUS_EX 
--

CREATE VIEW V_PLAN_STATUS_EX AS    
SELECT PL.PLAN_ID, PL.REC_NUM, PL.START_TIME, PL.COMPLETION_TIME, PL.STATUS, AC.IS_TEMPLATE, 
       AC.PRIORITY, AC.NAME, AC.STOP_ON_ERROR, AC.IS_CANC_CUTOFF, AC.DESCRIPTION, AC.REC_STOP_ON_ERROR,
       AC.REC_STOP_OVERLAP, AC.REC_TYPE, AC.DAYS_OF_WEEK, AC.DAYS_OF_MONTH, AC.REC_BY_DATE_INT,
       AC.REC_BY_TIME_INT, AC.IS_DYN_RESOLV, AC.MAIL_ADDRESS, AC.IS_POST_NOTICE, AC.NOT_BEFORE_TIME,
       AC.NOT_AFTER_TIME, PL.PREV_STATUS, AC.IS_PAUSED, AC.REC_EXPIRE_TIME, AC.ON_TERMINATION, A.ACTIVITIES
FROM ACT_PLAN_STATUS PL, ACTIVITY_PLAN AC,
    (SELECT COUNT(*) AS ACTIVITIES, PLAN_ID, REC_NUMBER FROM ACTIVITY_STATUS GROUP BY PLAN_ID, REC_NUMBER) A
WHERE PL.PLAN_ID = AC.PLAN_ID  AND AC.IS_TEMPLATE = 'S' AND A.PLAN_ID = AC.PLAN_ID AND A.REC_NUMBER = PL.REC_NUM
;

-- 
-- VIEW: V_TGT_ACT_DEP_ST 
--

CREATE VIEW V_TGT_ACT_DEP_ST AS    
SELECT AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.STATUS, AC.DEPOT_LABEL, 
COUNT(*) COUNTER, MIN(START_TIME) START_TIME, MAX(COMPLETION_TIME) COMPLETION_TIME   
FROM ACT_STATUS_TGT AC  
GROUP BY AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.DEPOT_LABEL, AC.STATUS
;

-- 
-- VIEW: V_TGT_ACT_GW_ST 
--

CREATE VIEW V_TGT_ACT_GW_ST AS    
SELECT AC.STATUS, AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.GATEWAY_LABEL, 
COUNT(*) COUNTER, MIN(START_TIME) START_TIME, MAX(COMPLETION_TIME) COMPLETION_TIME   
FROM ACT_STATUS_TGT AC  
GROUP BY AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.GATEWAY_LABEL, AC.STATUS
;

-- 
-- VIEW: V_TGT_ACT_ST 
--

CREATE VIEW V_TGT_ACT_ST AS    
SELECT AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.STATUS, COUNT(*) COUNTER    
FROM ACT_STATUS_TGT AC  
GROUP BY AC.PLAN_ID, AC.ACTIVITY_ID, AC.REC_NUMBER, AC.STATUS
;

-- 
-- VIEW: V_STATUS_FILTER
--
CREATE VIEW V_STATUS_FILTER  (
PLAN_ID, ACTIVITY_ID, PLAN_NAME, ACTIVITY_NAME,PLAN_STATUS,ACTIVITY_STATUS,PLAN_START_TIME,
PLAN_COMPL_TIME,ACT_START_TIME,ACT_COMPL_TIME,PLAN_REC_NUM,ACT_REC_NUM,
PLAN_PREV_STATUS,ACTIVITIES,TARGETS,GATEWAYS,DEPOTS)
AS
SELECT VPSE.PLAN_ID,VASE.ACTIVITY_ID,
VPSE.NAME,VASE.NAME,
VPSE.STATUS,VASE.STATUS,
VPSE.START_TIME,VPSE.COMPLETION_TIME,
VASE.START_TIME,VASE.COMPLETION_TIME,
VPSE.REC_NUM,
VASE.REC_NUMBER,
VPSE.PREV_STATUS,
VPSE.ACTIVITIES,
VASE.TARGETS,
VASE.GATEWAYS,
VASE.DEPOTS
FROM V_PLAN_STATUS_EX VPSE,V_ACT_STATUS_EX VASE
WHERE VPSE.PLAN_ID = VASE.PLAN_ID AND VPSE.REC_NUM = VASE.REC_NUMBER 
;
--
-- INDEXES ON FOREIGN KEY TO SPEED UP JOINS
--

-- 
-- INDEX: IX_FK_PLAN_STATUS 
--
CREATE INDEX IX_FK_PLAN_STATUS ON ACT_PLAN_STATUS(PLAN_ID)
;


--
-- INDEX: IX_FK_ACT_STATUS
--
CREATE INDEX IX_FK_ACT_STATUS ON ACTIVITY_STATUS(PLAN_ID, ACTIVITY_ID)
;


-- 
-- INDEX: IX_FK_ACT_PARAMETER 
--
CREATE INDEX IX_FK_ACT_PARAMETER ON ACT_PARAMETER(PLAN_ID,ACTIVITY_ID)
;


-- 
-- INDEX: IX_FK_ACT_STATUS_TGT
--
CREATE INDEX IX_FK_ACT_STATUS_TGT ON ACT_STATUS_TGT(PLAN_ID,REC_NUMBER, ACTIVITY_ID)
;


-- 
-- INDEX: IX_FK_VARIABLE 
--
CREATE INDEX IX_FK_VARIABLE ON VARIABLE(PLAN_ID)
;

--
-- REF. INTEGRITY CONSTRAINTS
-- 

-- 
-- TABLE: ACT_LAYOUT 
--

ALTER TABLE ACT_LAYOUT ADD CONSTRAINT FK_ACT_LAYOUT
    FOREIGN KEY (PLAN_ID,ACTIVITY_ID)
    REFERENCES ACTIVITY(PLAN_ID,ACTIVITY_ID) 
;


ALTER TABLE PLUGIN_FILE_INFO ADD CONSTRAINT FK_ACT_FINFO 
    FOREIGN KEY (APPLICATION_TYPE)
    REFERENCES APPL_OPERATION(APPLICATION_TYPE)
;

-- 
-- TABLE: APPL_ERRLEV 
--

ALTER TABLE APPL_ERRLEV ADD CONSTRAINT FK_APPL_ERRLEV
    FOREIGN KEY (APPLICATION_TYPE)
    REFERENCES APPL_OPERATION(APPLICATION_TYPE) 
;




-- 
-- TABLE: ACT_PARAMETER 
--

ALTER TABLE ACT_PARAMETER ADD CONSTRAINT FK_ACT_PARAMETER 
    FOREIGN KEY (PLAN_ID,ACTIVITY_ID)
    REFERENCES ACTIVITY(PLAN_ID,ACTIVITY_ID) 
;


-- 
-- TABLE: ACT_PLAN_STATUS 
--

ALTER TABLE ACT_PLAN_STATUS ADD CONSTRAINT FK_ACT_PLAN_STATUS 
    FOREIGN KEY (PLAN_ID)
    REFERENCES ACTIVITY_PLAN(PLAN_ID) 
;


-- 
-- TABLE: ACT_STATUS_TGT 
--

ALTER TABLE ACT_STATUS_TGT ADD CONSTRAINT FK_ACT_STATUS_TGT 
    FOREIGN KEY (PLAN_ID,REC_NUMBER,ACTIVITY_ID)
    REFERENCES ACTIVITY_STATUS(PLAN_ID,REC_NUMBER,ACTIVITY_ID) 
;


-- 
-- TABLE: ACT_TARGET_SPEC 
--

ALTER TABLE ACT_TARGET_SPEC ADD CONSTRAINT FK_ACT_TARGET_SPEC 
    FOREIGN KEY (PLAN_ID,ACTIVITY_ID)
    REFERENCES ACTIVITY(PLAN_ID,ACTIVITY_ID)
;


-- 
-- TABLE: ACTIVITY_TARGET
--

ALTER TABLE ACTIVITY_TARGET ADD CONSTRAINT FK_ACT_TARGET 
    FOREIGN KEY (PLAN_ID,ACTIVITY_ID)
    REFERENCES ACTIVITY(PLAN_ID,ACTIVITY_ID) 
;


-- 
-- TABLE: ACTIVITY 
--

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACT_PLAN  
    FOREIGN KEY (PLAN_ID)
    REFERENCES ACTIVITY_PLAN(PLAN_ID) 
;

ALTER TABLE ACTIVITY ADD CONSTRAINT FK_ACT_APPL  
    FOREIGN KEY (APPLICATION_TYPE)
    REFERENCES APPL_OPERATION(APPLICATION_TYPE)
;


-- 
-- TABLE: ACTIVITY_STATUS 
--

ALTER TABLE ACTIVITY_STATUS ADD CONSTRAINT FK_ACT_STATUS  
    FOREIGN KEY (PLAN_ID,ACTIVITY_ID)
    REFERENCES ACTIVITY(PLAN_ID,ACTIVITY_ID) 
;


-- 
-- TABLE: EXECUTION_WINDOW 
--

ALTER TABLE EXECUTION_WINDOW ADD CONSTRAINT FK_EXEC_WINDOW  
    FOREIGN KEY (PLAN_ID,ACTIVITY_ID)
    REFERENCES ACTIVITY(PLAN_ID,ACTIVITY_ID) 
;


-- 
-- TABLE: PLAN_TARGET_SPEC 
--

ALTER TABLE PLAN_TARGET_SPEC ADD CONSTRAINT FK_PLAN_TGT_SPEC 
    FOREIGN KEY (PLAN_ID)
    REFERENCES ACTIVITY_PLAN(PLAN_ID) 
;


-- 
-- TABLE: PLAN_TARGET
--

ALTER TABLE PLAN_TARGET ADD CONSTRAINT FK_PLAN_TARGET
    FOREIGN KEY (PLAN_ID)
    REFERENCES ACTIVITY_PLAN(PLAN_ID) 
;


-- 
-- TABLE: VARIABLE 
--

ALTER TABLE VARIABLE ADD CONSTRAINT FK_VARIABLE 
    FOREIGN KEY (PLAN_ID)
    REFERENCES ACTIVITY_PLAN(PLAN_ID) 
;


COMMIT;

spool off;

exit;
