--
-- Licensed Materials - Property of IBM 
--  
-- (C)IBM Corp. 2000, 2002. 
-- All Rights Reserved. US Government Users Restricted Rights 
-- Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
--
--
-- IBM Tivoli Configuration Manager
-- Pristine Manager
-- Database schema creation script 
-- Platform: Oracle
--

-- 
spool fs_pristine_ora_schema.log;

------------
-- TABLES --
------------

-- Dropping existing constraints and tables --

--ALTER TABLE SERVER_ENVIRONMENT DROP CONSTRAINT FK_ENV;

--ALTER TABLE SERVER DROP CONSTRAINT FK_SERVER;

--ALTER TABLE PLUGIN_ENVIRONMENT DROP CONSTRAINT FK_PLUGIN_ENV;

--ALTER TABLE ROLE_SUBSCRIBER DROP CONSTRAINT FK_ROLE_SUBSCRIBER;

--ALTER TABLE ROLE_SUBSCRIBER DROP CONSTRAINT FK_MACH_SUBSCRIBER;

--ALTER TABLE MACHINE_ENV DROP CONSTRAINT FK_MACHINE_ENV;

--ALTER TABLE MACHINE DROP CONSTRAINT FK_MACHINE;

--ALTER TABLE MACHINE DROP CONSTRAINT FK_TMR_NAME;

--ALTER TABLE OSELEMENT_IMAGE DROP CONSTRAINT FK__IMAGE;

--ALTER TABLE OSELEMENT_IMAGE DROP CONSTRAINT FK__OSELEMENT;

--ALTER TABLE IMAGE DROP CONSTRAINT FK_IMAGE_SERVER;

--ALTER TABLE PLUGIN_CREATE_KEYS DROP CONSTRAINT FK_PLUGIN;

--DROP TABLE SERVER_ENVIRONMENT;

--DROP TABLE PRISTINE_ROLE;

--DROP TABLE ROLE_SUBSCRIBER;

--DROP TABLE SERVER;

--DROP TABLE PLUGIN_ENVIRONMENT;

--DROP TABLE MACHINE_ENV;

--DROP TABLE MACHINE;

--DROP TABLE OSELEMENT_IMAGE;

--DROP TABLE OSELEMENT;

--DROP TABLE IMAGE;

--DROP TABLE PLUGIN_CREATE_KEYS;

--DROP TABLE PLUGIN;

--DROP TABLE PRISTINE_ACTIVITY;

--DROP TABLE SUPPORTED_OS;

--DROP TABLE TMR_NAME;

-- Creating tables and constraints --

CREATE TABLE SERVER_ENVIRONMENT (
	ENV_KEY 		VARCHAR ( 32 ) NOT NULL,
	ENV_VALUE 		VARCHAR ( 254 ) NOT NULL,
	SERVER_NAME 	VARCHAR ( 64 ) NOT NULL,
	CONSTRAINT 	PK_ENV PRIMARY KEY (SERVER_NAME, ENV_KEY)
	);

CREATE TABLE SERVER (
	NAME 		VARCHAR ( 64 ) NOT NULL,
	TYPE 		VARCHAR ( 16 ) NOT NULL,
	DESCRIPTION 	VARCHAR ( 128 ),
	EP_LABEL 	VARCHAR ( 254 ) NOT NULL,
	CONSTRAINT 	PK_SERVER PRIMARY KEY (NAME),
	CONSTRAINT 	TC_SERVER UNIQUE (EP_LABEL)
	);

CREATE TABLE PLUGIN_ENVIRONMENT (
	ENV_KEY 		VARCHAR ( 32 ) NOT NULL,
	ENV_VALUE 		VARCHAR ( 254 ) NOT NULL,
	PLUGIN_NAME 	VARCHAR ( 16 ) NOT NULL,
	CONSTRAINT 	PK_PLUGIN_ENV PRIMARY KEY (PLUGIN_NAME, ENV_KEY)
	);

CREATE TABLE MACHINE_ENV (
	ENV_KEY 		VARCHAR ( 32 ) NOT NULL,
	ENV_VALUE 		VARCHAR ( 254 ) NOT NULL,
	MACHINE_LABEL 	VARCHAR ( 190 ) NOT NULL,
	CONSTRAINT 	PK_MACHINE_ENV PRIMARY KEY (MACHINE_LABEL, ENV_KEY)
	);

CREATE TABLE MACHINE (
	LABEL 		VARCHAR ( 190 ) NOT NULL,
	SERVER_NAME 	VARCHAR ( 64 ) NOT NULL,
	MACHINE_ID 	VARCHAR ( 128 ),
	PRISTINE_MODE 	INTEGER NOT NULL,
	DESCRIPTION 	VARCHAR ( 128 ),
	TMR_NAME        VARCHAR ( 128 ) NOT NULL,
	CONSTRAINT 	PK_MACHINE PRIMARY KEY (LABEL)
	);

CREATE TABLE TMR_NAME (
    NAME            VARCHAR ( 128 ) NOT NULL,
    PD_OBJREF       VARCHAR ( 128 ) NOT NULL,
    CONSTRAINT      PK_TMR_NAME PRIMARY KEY (NAME)
    );

CREATE TABLE PRISTINE_ROLE (
	NAME 		VARCHAR ( 64 ) NOT NULL,
	DESCRIPTION 	VARCHAR ( 128 ),
	CONSTRAINT 	PK_ROLE PRIMARY KEY (NAME)
	);

CREATE TABLE ROLE_SUBSCRIBER (
	PRISTINE_ROLE	VARCHAR ( 64 ) NOT NULL,
	MACHINE 	VARCHAR ( 190 ) NOT NULL,
	CONSTRAINT 	PK_ROLE_SUBSCRIBER PRIMARY KEY (MACHINE, PRISTINE_ROLE)
	);

CREATE TABLE OSELEMENT_IMAGE (
	SERVER VARCHAR ( 64 ) NOT NULL,
	IMAGE VARCHAR ( 190 ) NOT NULL,
	OSELEMENT VARCHAR ( 64 ) NOT NULL,
	CONSTRAINT PK_OSELEMENT_IMAGE PRIMARY KEY (OSELEMENT, SERVER)
	);

CREATE TABLE OSELEMENT (
	LABEL 		VARCHAR ( 64 ) NOT NULL,
	DESCRIPTION 	VARCHAR ( 128 ),
	OSNAME 		VARCHAR ( 32 ),
	OSVERSION	VARCHAR ( 32 ),
	ARCHITECTURE 	VARCHAR ( 32 ),
	CONSTRAINT 	PK_OSELEMENT PRIMARY KEY (LABEL)
	);

CREATE TABLE IMAGE (
	NAME 		VARCHAR ( 190 ) NOT NULL,
	DESCRIPTION 	VARCHAR ( 128 ),
	SERVER_NAME 	VARCHAR ( 64 ) NOT NULL,
	OSNAME 		VARCHAR ( 32 ),
	OSVERSION 	VARCHAR ( 32 ),
	ARCHITECTURE 	VARCHAR ( 32 ),
	MIN_PROCESSORS 	INTEGER,
	MAX_PROCESSORS 	INTEGER,
	DISKSPACE 	INTEGER,
	MEMORY 		INTEGER,
	CONSTRAINT 	PK_IMAGE PRIMARY KEY (SERVER_NAME, NAME)
	);

CREATE TABLE PLUGIN (
	NAME 		VARCHAR ( 16 ) NOT NULL,
	VERSION 	VARCHAR ( 16 ) NOT NULL,
	CONSTRAINT 	PK_PLUGIN PRIMARY KEY (NAME)
	);

CREATE TABLE PLUGIN_CREATE_KEYS (
    PLUGIN_NAME VARCHAR ( 16 ) NOT NULL,
    ENV_KEY     VARCHAR ( 32 ) NOT NULL,
    CONSTRAINT  PK_PLUGIN_KEYS PRIMARY KEY (PLUGIN_NAME, ENV_KEY)
    );

CREATE TABLE PRISTINE_ACTIVITY (
	LABEL                   VARCHAR ( 190 ) NOT NULL,
	PD_OBJREF               VARCHAR ( 128 ) NOT NULL,
	SERVER_NAME             VARCHAR ( 64 ),
	OS_ELEMENT              VARCHAR ( 64 ) NOT NULL,
	APM_PLAN_ID             VARCHAR ( 80 ) NOT NULL,
	APM_OBJREF              VARCHAR ( 128 ) NOT NULL,
	STATE                   INTEGER NOT NULL,
	COMPLETION_STATE        INTEGER NOT NULL,
	TIME_CREATED            INTEGER NOT NULL,
	MESSAGE_CODE            INTEGER NOT NULL,
	CONSTRAINT              PK_ACTIVITY PRIMARY KEY (LABEL)
	);
	
	
CREATE TABLE SUPPORTED_OS (
    OS_NAME             VARCHAR ( 254 ) NOT NULL,
    OS_TYPE             VARCHAR ( 64 ) NOT NULL,
    OS_ALIAS            VARCHAR ( 16 ) NOT NULL,
    OS_MAJOR_VERSION    INTEGER NOT NULL,
    OS_MINOR_VERSION    INTEGER NOT NULL,
    CONSTRAINT          PK_OS PRIMARY KEY (OS_NAME)
);

	
ALTER TABLE SERVER_ENVIRONMENT
	ADD CONSTRAINT FK_ENV FOREIGN KEY (SERVER_NAME)
	REFERENCES SERVER (NAME);

ALTER TABLE SERVER
	ADD CONSTRAINT FK_SERVER FOREIGN KEY (TYPE)
	REFERENCES PLUGIN (NAME);

ALTER TABLE PLUGIN_ENVIRONMENT
	ADD CONSTRAINT FK_PLUGIN_ENV FOREIGN KEY (PLUGIN_NAME)
	REFERENCES PLUGIN (NAME);

ALTER TABLE MACHINE_ENV
	ADD CONSTRAINT FK_MACHINE_ENV FOREIGN KEY (MACHINE_LABEL)
	REFERENCES MACHINE (LABEL);

ALTER TABLE MACHINE
	ADD CONSTRAINT FK_MACHINE FOREIGN KEY (SERVER_NAME)
	REFERENCES SERVER (NAME);

ALTER TABLE MACHINE
	ADD CONSTRAINT FK_TMR_NAME FOREIGN KEY (TMR_NAME)
	REFERENCES TMR_NAME (NAME);

ALTER TABLE ROLE_SUBSCRIBER
	ADD CONSTRAINT FK_ROLE_SUBSCRIBER FOREIGN KEY (PRISTINE_ROLE)
	REFERENCES PRISTINE_ROLE (NAME);

ALTER TABLE ROLE_SUBSCRIBER
	ADD CONSTRAINT FK_MACH_SUBSCRIBER FOREIGN KEY (MACHINE)
	REFERENCES MACHINE (LABEL);

ALTER TABLE OSELEMENT_IMAGE
	ADD CONSTRAINT FK__IMAGE FOREIGN KEY (SERVER, IMAGE)
	REFERENCES IMAGE (SERVER_NAME, NAME);
	
ALTER TABLE OSELEMENT_IMAGE
	ADD CONSTRAINT FK__OSELEMENT FOREIGN KEY (OSELEMENT)
	REFERENCES OSELEMENT (LABEL);

ALTER TABLE IMAGE
	ADD CONSTRAINT FK_IMAGE_SERVER FOREIGN KEY (SERVER_NAME)
	REFERENCES SERVER (NAME);

ALTER TABLE PLUGIN_CREATE_KEYS
	ADD CONSTRAINT FK_PLUGIN FOREIGN KEY (PLUGIN_NAME)
	REFERENCES PLUGIN (NAME);


INSERT INTO PLUGIN 
	VALUES ('RIS', '1.0');

INSERT INTO PLUGIN
	VALUES ('ADS', '1.0');

-- insert plugin create keys for RIS 

INSERT INTO PLUGIN_CREATE_KEYS
    VALUES ('RIS', 'PRISTINE_COMPUTERNAME');

INSERT INTO PLUGIN_CREATE_KEYS
    VALUES ('RIS', 'PRISTINE_SMBIOS_GUID');


-- insert plugin create keys for ADS

INSERT INTO PLUGIN_CREATE_KEYS
    VALUES ('ADS', 'PRISTINE_HOSTNAME');

INSERT INTO PLUGIN_CREATE_KEYS
    VALUES ('ADS', 'PRISTINE_SMBIOS_GUID');

INSERT INTO PLUGIN_CREATE_KEYS
    VALUES ('ADS', 'PRISTINE_MAC_ADDRESS');


-- insert supported operating systems 

INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows 2000', '_Win32_NT', 'Win2000', 5, 0 );

INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows XP', '_Win32_NT', 'WinXP', 5, 1 );
    
INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows 2003', '_Win32_NT', 'Win2003', 5, 2 );

INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows NT', '_Win32_NT', 'WinNT', 4, 0 );

INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows 95', '_Win32_Windows', 'Win95', 4, 0 );

INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows 98', '_Win32_Windows', 'Win98', 4, 10 );

INSERT INTO SUPPORTED_OS
    VALUES ('Microsoft Windows Millennium', '_Win32_Windows', 'WinME', 4, 90 );

COMMIT;

spool off;

exit

