--
--
-- Licensed Materials - Property of IBM
--
-- 5698-INV
--
-- (C) Copyright IBM Corp. 2002, 2005 All Rights Reserved
--
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp
--
--
--
-- This script is to upgrade a CM 4.2.3 installation.
-- Use inv_ora_schema.sql script for a fresh install.
--

---------------------------------------------------------------------

-- spool inv_ora_schema_423_FP07.log;
spool fs_inv_ora_schema_423_FP07.log;

--begin section added in 4.2.3.6-TIV-TCM-IF0002

alter table COMPUTER modify (SYS_SER_NUM varchar2(64));
commit;

ALTER TABLE T_FILE_DESC add CONSTRAINT FILEDESC_T_PK PRIMARY KEY (FILE_DESC_ID);
commit;

drop view PHYSICAL_PROCESSOR_VIEW;
create or replace view PHYSICAL_PROCESSOR_VIEW
as
select
    COMPUTER.TME_OBJECT_LABEL,
    COMPUTER.TME_OBJECT_ID,
    COMPUTER.COMPUTER_SYS_ID,
    PHYSICAL_PROCESSOR.BRANDNAME,
    PHYSICAL_PROCESSOR.CORE_PER_PK_COUNT,
    PHYSICAL_PROCESSOR.LOG_PROC_PER_CORE,
    PHYSICAL_PROCESSOR.MANUFACTURER,
    PHYSICAL_PROCESSOR.FAMILY,
    PHYSICAL_PROCESSOR.TYPE,
    PHYSICAL_PROCESSOR.CPU_FREQ,
    PHYSICAL_PROCESSOR.L2_CACHE_SIZE,
    PHYSICAL_PROCESSOR.L3_CACHE_SIZE,
    PHYSICAL_PROCESSOR.SIGNATURE,
    PHYSICAL_PROCESSOR.RECORD_TIME
from
    PHYSICAL_PROCESSOR,COMPUTER
where
    PHYSICAL_PROCESSOR.COMPUTER_SYS_ID = COMPUTER.COMPUTER_SYS_ID
;

drop view SIG_PACKAGE_VIEW;
create or replace view SIG_PACKAGE_VIEW
as
select
    COMPUTER.TME_OBJECT_LABEL,
    COMPUTER.TME_OBJECT_ID,
    COMPUTER.COMPUTER_SYS_ID,
    MATCHED_SIG_COUNT.SWARE_DESC,
    MATCHED_SIG_COUNT.SWARE_VERS
from
    COMPUTER,SIG_PACKAGE_COUNT,MATCHED_SIG_COUNT
where
    COMPUTER.COMPUTER_SYS_ID = MATCHED_SIG_COUNT.COMPUTER_SYS_ID
and
    SIG_PACKAGE_COUNT.SIG_PACKAGE_ID=MATCHED_SIG_COUNT.SIG_PACKAGE_ID
and
    SIG_PACKAGE_COUNT.NUM = MATCHED_SIG_COUNT.NUM
;

--end section added in 4.2.3.6-TIV-TCM-IF0002


alter table LPAR add PHYS_SHAREDPC varchar2(64);
alter table LPAR add PHYS_SHAREDPC_CORES varchar2(64);
alter table LPAR add LPAR_ONLINE_VP_COUNT varchar2(64);
alter table LPAR add LPAR_IS_SHARED_TYPE varchar2(1);
alter table LPAR add LPAR_IS_CAPPED varchar2(1);
alter table LPAR add LPAR_ENTITLEMENT varchar2(64);
alter table LPAR add LPAR_MIN_VP_COUNT varchar2(64);
alter table LPAR add LPAR_MAX_VP_COUNT varchar2(64);
alter table LPAR add LPAR_MIN_CAPACITY varchar2(64);
alter table LPAR add LPAR_MAX_CAPACITY varchar2(64);
alter table LPAR add LPAR_IDLE_CP_WEIGHT varchar2(64);
alter table LPAR add SMT_IS_ENABLED varchar2(1);
alter table LPAR add NODE_ACT_PROC_COUNT varchar2(64);

create or replace view LPAR_VIEW
as
select
    COMPUTER.TME_OBJECT_LABEL,
    COMPUTER.TME_OBJECT_ID,
    COMPUTER.COMPUTER_SYS_ID,
    COMPUTER.COMPUTER_ALIAS AS COMPUTER_NAME,
    LPAR.LPARID,
    LPAR.SHARED_POOL_ID,
    LPAR.NODE_CAPACITY,
    LPAR.NODECAP_IN_CORES,
    LPAR.LPAR_CAPACITY,
    LPAR.LPARCAP_IN_CORES,
    LPAR.SHARED_POOL_CAPACITY,
    LPAR.SHAREDPC_IN_CORES,
    LPAR.PHYS_SHAREDPC,
    LPAR.PHYS_SHAREDPC_CORES,
    LPAR.LPAR_ONLINE_VP_COUNT,
    LPAR.LPAR_IS_SHARED_TYPE,
    LPAR.LPAR_IS_CAPPED,
    LPAR.LPAR_ENTITLEMENT,
    LPAR.LPAR_MIN_VP_COUNT,
    LPAR.LPAR_MAX_VP_COUNT,
    LPAR.LPAR_MIN_CAPACITY,
    LPAR.LPAR_MAX_CAPACITY,
    LPAR.LPAR_IDLE_CP_WEIGHT,
    LPAR.SMT_IS_ENABLED,
    LPAR.NODE_ACT_PROC_COUNT,
    LPAR.SERIAL_NUMBER,
    to_char(LPAR.RECORD_TIME,'YYYY.MM.DD HH24:MI:SS') as RECORD_TIME
from
    LPAR, COMPUTER
where
    LPAR.COMPUTER_SYS_ID = COMPUTER.COMPUTER_SYS_ID
;

create or replace view LOGICAL_PARTITIONS_VIEW
as
select
    COMPUTER_NAME,
    SERIAL_NUMBER,
    COMPUTER_SYS_ID,
    LPARID,
    LPAR_CAPACITY,
    LPARCAP_IN_CORES,
    NODE_CAPACITY,
    NODECAP_IN_CORES,
    SHARED_POOL_ID,
    SHARED_POOL_CAPACITY,
    SHAREDPC_IN_CORES,
    PHYS_SHAREDPC,
    PHYS_SHAREDPC_CORES,
    LPAR_ONLINE_VP_COUNT,
    LPAR_IS_SHARED_TYPE,
    LPAR_IS_CAPPED,
    LPAR_ENTITLEMENT,
    LPAR_MIN_VP_COUNT,
    LPAR_MAX_VP_COUNT,
    LPAR_MIN_CAPACITY,
    LPAR_MAX_CAPACITY,
    LPAR_IDLE_CP_WEIGHT,
    SMT_IS_ENABLED,
    NODE_ACT_PROC_COUNT,
    RECORD_TIME
from
    LPAR_VIEW
where
    LPAR_CAPACITY NOT LIKE '-1%'
;

alter table FILE_DESC add FILE_SIZE_KB INTEGER;

create or replace view INST_FILE_VIEW
as
select
    COMPUTER.TME_OBJECT_LABEL,
    COMPUTER.TME_OBJECT_ID,
    COMPUTER.COMPUTER_SYS_ID,
    FILE_DESC.FILE_NAME,
    FILE_DESC.FILE_SIZE,
    FILE_DESC.FILE_SIZE_KB,
    FILE_PATH.PATH,
    to_char(UNMATCHED_FILES.CREATED_TIME,'YYYY.MM.DD HH24:MI:SS') as CREATED_TIME,
    to_char(UNMATCHED_FILES.MODIFIED_TIME,'YYYY.MM.DD HH24:MI:SS') as MODIFIED_TIME,
    to_char(UNMATCHED_FILES.ACCESSED_TIME,'YYYY.MM.DD HH24:MI:SS') as ACCESSED_TIME,
    UNMATCHED_FILES.FILE_PERMISSIONS,
    UNMATCHED_FILES.FILE_OWNER,
    UNMATCHED_FILES.FILE_GROUP,
    UNMATCHED_FILES.CHECKSUM_QUICK,
    UNMATCHED_FILES.CHECKSUM_CRC32,
    UNMATCHED_FILES.CHECKSUM_MD5,
    to_char(UNMATCHED_FILES.RECORD_TIME,'YYYY.MM.DD HH24:MI:SS') as RECORD_TIME
from
    UNMATCHED_FILES,COMPUTER,FILE_PATH,FILE_DESC
where
    UNMATCHED_FILES.COMPUTER_SYS_ID = COMPUTER.COMPUTER_SYS_ID
and
    FILE_PATH.FILE_PATH_ID = UNMATCHED_FILES.INST_PATH_ID
and
    FILE_DESC.FILE_DESC_ID = UNMATCHED_FILES.FILE_DESC_ID
;

insert into SCHEMA_VERS values ('CM 4.2.3', SYSDATE, 'PATCH',
'inv_ora_schema_423_FP07.sql', 'FP07 applied to existing installation')
;
commit;


spool off;

exit;

